"""empty message

Revision ID: 07c846834a95
Revises: 953eed4296ff
Create Date: 2022-10-06 07:37:12.542259

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '07c846834a95'
down_revision = '953eed4296ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
